version: 2

models:
  - name: fact_bank
    description: "a"
    columns:
      - name: id
        description: "Fact table primary key"    
      - name: job_id
        description: "Identifier for job types"
        tests:
          - not_null
          - relationships:
              to: ref('dim_job')
              field: job_id
      - name: education_id
        description: "Identifier for education types"
        tests:
          - not_null
          - relationships:
              to: ref('dim_education')
              field: education_id
      - name: marital_id
        description: "Identifier for marital types"      
        tests:
          - not_null
          - relationships:
              to: ref('dim_marital')
              field: marital_id
      - name: contact_id
        description: "Identifier for contact types"      
        tests:
          - not_null
          - relationships:
              to: ref('dim_contact')
              field: contact_id              
      - name: age
        description: "a"
      - name: month
        description: "a"
      - name: day_of_week
        description: "a"
      - name: credit
        description: "a"
      - name: housing_loan
        description: "a"
      - name: personal_loan
        description: "a"
      - name: subscribe
        description: "a"

  - name: dim_job
    description: "a"
    columns:
    - name: job_id
      tests:
        - unique
        - not_null
    columns:
    - name: job_type
      tests:
        - not_null
        - accepted_values:
            values: ['housemaid', 'services', 'admin.', 'blue-collar', 'technician', 'retired', 'management', 'unemployed', 'self-employed', 'unknown', 'entrepreneur', 'student']
            
  - name: dim_education
    description: "a"
    columns:
    - name: education_id
      tests:
        - not_null
        - unique
    columns:
    - name: education_type
      tests:
        - not_null
        - accepted_values:
            values: ['basic', 'high.school', 'professional.course', 'unknown', 'university.degree', 'illiterate']      

  - name: dim_marital
    description: "a"
    columns:
    - name: marital_id
      tests:
        - not_null
        - unique
    columns:
    - name: marital_type
      tests:
        - not_null
        - accepted_values:
            values: ['married', 'single', 'divorced', 'unknown']

  - name: dim_contact
    description: "a"
    columns:
    - name: contact_id
      tests:
        - not_null
        - unique
    columns:
    - name: contact_type
      tests:
        - not_null
        - accepted_values:
            values: ['telephone', 'cellular']             